// Generated by CoffeeScript 1.6.1
(function() {
$(document).on("click", "#tutorial", function(e) {
e.preventDefault();
$(this).addClass("btn-link");
$("#step-by-step-wrapper").removeClass("collapsed");
return setTimeout(function() {
return $("body").chardinJs("start");
}, 300);
});
$(document).on("click", "#step-by-step", function(e) {
e.preventDefault();
$("body").chardinJs("stop");
return setTimeout(function() {
return introJs().start();
}, 300);
});
}).call(this);