// Generated by CoffeeScript 1.6.1
(function() {
impress().init();
$(".arrow").each(function(e, t) {
var n, r, i, s, o, u, a, f, l, c, h;
n = $(t);
n.html('<div class="arrow-stem arrow-left"></div>\n<div class="label">' + n.data("label") + '</div>\n<div class="arrow-stem arrow-right"></div>\n<div class="arrow-tip"></div>');
r = n.css({
width: n.data("width")
}).find(".label");
i = parseInt(n.css("width"), 10);
n.data("y-offset") ? h = parseInt(n.data("y-offset"), 10) : h = 0;
n.data("right-y-offset") ? a = parseInt(n.data("right-y-offset"), 10) : a = 0;
s = n.data("direction");
s == null && (s = "right");
c = parseInt(r.css("width"), 10);
l = parseInt(r.css("height"), 10);
f = (i - c) / 2 - 5;
o = {};
o.rotation = Math.atan(h / f);
o.rotationDeg = o.rotation * (180 / Math.PI);
o.stemLength = Math.sqrt(Math.pow(f, 2) + Math.pow(h, 2));
o.rotationalSideShift = o.stemLength * (1 - Math.cos(o.rotation));
u = {};
u.rotation = Math.atan((h - a) / f);
u.rotationDeg = u.rotation * (180 / Math.PI);
u.stemLength = Math.sqrt(Math.pow(f, 2) + Math.pow(h - a, 2));
u.rotationalSideShift = u.stemLength * (1 - Math.cos(u.rotation));
r.css({
left: (i - c) / 2,
top: h
});
n.find(".arrow-left").css({
top: (l + h) / 2,
width: o.stemLength,
left: -o.rotationalSideShift / 2,
transform: "rotate(" + o.rotationDeg + "deg)"
});
n.find(".arrow-right").css({
top: (l + h + a) / 2,
width: u.stemLength,
right: -u.rotationalSideShift / 2,
transform: "rotate(" + -u.rotationDeg + "deg)"
});
return s === "left" ? n.find(".arrow-tip").css({
left: -4,
top: l / 2 - 4,
transform: "rotate(" + o.rotationDeg + "deg)"
}) : n.find(".arrow-tip").css({
right: -4,
top: l / 2 + a - 5,
transform: "rotate(" + (180 - u.rotationDeg) + "deg)"
});
});
}).call(this);